openapi: 3.0.0
info:
  title: Acorn Hunt Game Microservice
  description: |
    API to perform in-game actions
  version: 1.0.0

paths:
  /points:
    post:
      summary: Add or remove points from the caller in their active game
      operationId: updatePoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - count
              properties:
                count:
                  type: integer
                  minimum: -10
                  maximum: 10                
      responses:
        200:
          description: The points were successfully added to the player score
          content:
            application/json:
              schema:
                type: object
                required:
                  - score
                properties:
                  score:
                    type: integer
        409:
          $ref: '#/components/responses/Conflict'
        500:
          $ref: '#/components/responses/UnknownError'      

  /super-abilities:
    post:
      summary: Add super-ability uses to the caller for their active game
      operationId: increaseSuperAbility
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - count
              properties:
                count:
                  type: integer
                  minimum: 1
                  maximum: 3                
      responses:
        200:
          description: The uses were added to the caller
          content:
            application/json:
              schema:
                type: object
                required:
                  - remaining
                properties:
                  remaining:
                    type: integer
        409:
          $ref: '#/components/responses/Conflict'
        500:
          $ref: '#/components/responses/UnknownError'
    delete:
      summary: Remves a super-ability use for the caller in the active game
      operationId: decreaseSuperAbility
      responses:
        200:
          description: The super-ability count decreased
          content:
            application/json:
              schema:
                type: object
                required:
                  - remaining
                properties:
                  remaining:
                    type: integer
        409:
          $ref: '#/components/responses/Conflict'
        500:
          $ref: '#/components/responses/UnknownError'

components:
  responses:
    BadRequest:
      description: Invalid input was provided
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                example: Invalid input was provided

    Conflict:
      description: Unable to process request due to the state of the entity
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                example: You are not part of an active game

    UnknownError:
      description: An unexpected error occurred on the server.
      content:
        application/json:
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                description: Unknown error message
                example: An unexpected error occurred.